# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='embedding.proto',
  package='embedding',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x65mbedding.proto\x12\tembedding\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\nEmbedReply\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32\x44\n\x07\x45mbeder\x12\x39\n\x05\x45mbed\x12\x17.embedding.EmbedRequest\x1a\x15.embedding.EmbedReply\"\x00\x62\x06proto3'
)




_EMBEDREQUEST = _descriptor.Descriptor(
  name='EmbedRequest',
  full_name='embedding.EmbedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='embedding.EmbedRequest.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=59,
)


_EMBEDREPLY = _descriptor.Descriptor(
  name='EmbedReply',
  full_name='embedding.EmbedReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='embedding', full_name='embedding.EmbedReply.embedding', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['EmbedRequest'] = _EMBEDREQUEST
DESCRIPTOR.message_types_by_name['EmbedReply'] = _EMBEDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmbedRequest = _reflection.GeneratedProtocolMessageType('EmbedRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDREQUEST,
  '__module__' : 'embedding_pb2'
  # @@protoc_insertion_point(class_scope:embedding.EmbedRequest)
  })
_sym_db.RegisterMessage(EmbedRequest)

EmbedReply = _reflection.GeneratedProtocolMessageType('EmbedReply', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDREPLY,
  '__module__' : 'embedding_pb2'
  # @@protoc_insertion_point(class_scope:embedding.EmbedReply)
  })
_sym_db.RegisterMessage(EmbedReply)



_EMBEDER = _descriptor.ServiceDescriptor(
  name='Embeder',
  full_name='embedding.Embeder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=94,
  serialized_end=162,
  methods=[
  _descriptor.MethodDescriptor(
    name='Embed',
    full_name='embedding.Embeder.Embed',
    index=0,
    containing_service=None,
    input_type=_EMBEDREQUEST,
    output_type=_EMBEDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMBEDER)

DESCRIPTOR.services_by_name['Embeder'] = _EMBEDER

# @@protoc_insertion_point(module_scope)
